// This file is auto-generated by generate-llm-config.mts
// Do not edit this file directly

// Define the type for category configuration
export type CategoryConfig = {
  title: string;
  description: string;
  patterns: string[];
  excludePatterns?: string[];
};

// Define the type for the complete configuration map with an index signature
export type CategoryConfigMap = Record<string, CategoryConfig>;

// Auto-generated category configuration
export const categoryConfig: CategoryConfigMap = {
  "all": {
    "title": "All MeetingBaas documentation content",
    "description": "This contains all documentation across Meeting BaaS systems. Each section below is from a different part of the documentation.",
    "patterns": [
      "./content/docs/**/*.mdx"
    ]
  },
  "api": {
    "title": "MeetingBaas API, the main purpose of the documentation",
    "description": "API documentation for interacting with Meeting BaaS services.",
    "patterns": [
      "./content/docs/api/**/*.mdx"
    ]
  },
  "api/all": {
    "title": "Complete MeetingBaas API Reference",
    "description": "Complete API reference for all MeetingBaas endpoints generated from OpenAPI specifications.",
    "patterns": [
      "./content/docs/api/reference/**/*.mdx"
    ]
  },
  "api/calendars": {
    "title": "calendars api Reference",
    "description": "Reference documentation for calendars in api.",
    "patterns": [
      "./content/docs/api/reference/calendars/**/*.mdx"
    ]
  },
  "calendars": {
    "title": "Calendars API, for managing calendar integrations and events",
    "description": "Documentation for calendar integration endpoints and functionality.",
    "patterns": [
      "./content/docs/api-v2/reference/calendars/**/*.mdx"
    ]
  },
  "api/webhooks": {
    "title": "webhooks api Reference",
    "description": "Reference documentation for webhooks in api.",
    "patterns": [
      "./content/docs/api/reference/webhooks/**/*.mdx"
    ]
  },
  "webhooks": {
    "title": "Webhooks API, for event notifications and integrations",
    "description": "Documentation for webhook integration endpoints and functionality.",
    "patterns": [
      "./content/docs/api-v2/reference/webhooks/**/*.mdx"
    ]
  },
  "api/zoom--o-auth": {
    "title": "zoom--o-auth api Reference",
    "description": "Reference documentation for zoom--o-auth in api.",
    "patterns": [
      "./content/docs/api/reference/zoom--o-auth/**/*.mdx"
    ]
  },
  "api-v2": {
    "title": "api-v2 Documentation",
    "description": "Documentation for api-v2.",
    "patterns": [
      "./content/docs/api-v2/**/*.mdx"
    ]
  },
  "api-v2/all": {
    "title": "Complete api-v2 Reference",
    "description": "Complete reference for api-v2.",
    "patterns": [
      "./content/docs/api-v2/reference/**/*.mdx"
    ]
  },
  "api-v2/bots": {
    "title": "bots api-v2 Reference",
    "description": "Reference documentation for bots in api-v2.",
    "patterns": [
      "./content/docs/api-v2/reference/bots/**/*.mdx"
    ]
  },
  "api-v2/calendars": {
    "title": "calendars api-v2 Reference",
    "description": "Reference documentation for calendars in api-v2.",
    "patterns": [
      "./content/docs/api-v2/reference/calendars/**/*.mdx"
    ]
  },
  "api-v2/callbacks": {
    "title": "callbacks api-v2 Reference",
    "description": "Reference documentation for callbacks in api-v2.",
    "patterns": [
      "./content/docs/api-v2/reference/callbacks/**/*.mdx"
    ]
  },
  "api-v2/webhooks": {
    "title": "webhooks api-v2 Reference",
    "description": "Reference documentation for webhooks in api-v2.",
    "patterns": [
      "./content/docs/api-v2/reference/webhooks/**/*.mdx"
    ]
  },
  "api-v2/zoom--credentials": {
    "title": "zoom--credentials api-v2 Reference",
    "description": "Reference documentation for zoom--credentials in api-v2.",
    "patterns": [
      "./content/docs/api-v2/reference/zoom--credentials/**/*.mdx"
    ]
  },
  "mcp-servers": {
    "title": "mcp-servers Documentation",
    "description": "Documentation for mcp-servers.",
    "patterns": [
      "./content/docs/mcp-servers/**/*.mdx"
    ]
  },
  "speaking-bots": {
    "title": "Speaking Bots, the Pipecat-powered bots",
    "description": "Documentation for Speaking Bots powered by Pipecat.",
    "patterns": [
      "./content/docs/speaking-bots/**/*.mdx"
    ]
  },
  "speaking-bots/all": {
    "title": "Complete Speaking Bots API Reference",
    "description": "Complete API reference for all Speaking Bots endpoints generated from OpenAPI specifications.",
    "patterns": [
      "./content/docs/speaking-bots/reference/**/*.mdx"
    ]
  },
  "speaking-bots/bots": {
    "title": "bots speaking-bots Reference",
    "description": "Reference documentation for bots in speaking-bots.",
    "patterns": [
      "./content/docs/speaking-bots/reference/bots/**/*.mdx"
    ]
  },
  "speaking-bots/personas": {
    "title": "personas speaking-bots Reference",
    "description": "Reference documentation for personas in speaking-bots.",
    "patterns": [
      "./content/docs/speaking-bots/reference/personas/**/*.mdx"
    ]
  },
  "speaking-bots/system": {
    "title": "system speaking-bots Reference",
    "description": "Reference documentation for system in speaking-bots.",
    "patterns": [
      "./content/docs/speaking-bots/reference/system/**/*.mdx"
    ]
  },
  "transcript-seeker": {
    "title": "Transcript Seeker, the open-source transcription playground",
    "description": "Documentation for the Transcript Seeker transcription playground.",
    "patterns": [
      "./content/docs/transcript-seeker/**/*.mdx"
    ]
  },
  "typescript-sdk": {
    "title": "TypeScript SDK for MeetingBaas",
    "description": "TypeScript SDK documentation for programmatically interacting with Meeting BaaS APIs.",
    "patterns": [
      "./content/docs/typescript-sdk/**/*.mdx"
    ]
  },
  "updates": {
    "title": "updates Documentation",
    "description": "Documentation for updates.",
    "patterns": [
      "./content/docs/updates/**/*.mdx"
    ]
  }
};

// Auto-generated .txt redirect paths
export const knownTxtPaths: string[][] = [
  [],
  [
    "llms"
  ],
  [
    "llms",
    "all"
  ],
  [
    "llms",
    "api"
  ],
  [
    "llms",
    "api",
    "all"
  ],
  [
    "llms",
    "api",
    "calendars"
  ],
  [
    "llms",
    "calendars"
  ],
  [
    "llms",
    "api",
    "webhooks"
  ],
  [
    "llms",
    "webhooks"
  ],
  [
    "llms",
    "api",
    "zoom--o-auth"
  ],
  [
    "llms",
    "api-v2"
  ],
  [
    "llms",
    "api-v2",
    "all"
  ],
  [
    "llms",
    "api-v2",
    "bots"
  ],
  [
    "llms",
    "api-v2",
    "calendars"
  ],
  [
    "llms",
    "api-v2",
    "callbacks"
  ],
  [
    "llms",
    "api-v2",
    "webhooks"
  ],
  [
    "llms",
    "api-v2",
    "zoom--credentials"
  ],
  [
    "llms",
    "mcp-servers"
  ],
  [
    "llms",
    "speaking-bots"
  ],
  [
    "llms",
    "speaking-bots",
    "all"
  ],
  [
    "llms",
    "speaking-bots",
    "bots"
  ],
  [
    "llms",
    "speaking-bots",
    "personas"
  ],
  [
    "llms",
    "speaking-bots",
    "system"
  ],
  [
    "llms",
    "transcript-seeker"
  ],
  [
    "llms",
    "typescript-sdk"
  ],
  [
    "llms",
    "updates"
  ]
];
